/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package task3_University;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.IOException;
import java.io.InputStreamReader;

public class App {
    public static void main(String[] args) {
        UserInterface.Start();
    }
}
